### PR TITLE
Button ui border + TextFieldStyle + JXCalandar

### PR DESCRIPTION
**Pull request by jarek-insys**
Hi Vincent @vincenzopalazzo,

TextField Line style
MaterialConstants.TEXT_FIELD_STYLE_NONE - no line
MaterialConstants.TEXT_FIELD_STYLE_LINE - current line over component + fix position of line
MaterialConstants.TEXT_FIELD_STYLE_OUTLINE - outline over border
MaterialConstants.TEXT_FIELD_STYLE_BORDER_LINE - line over border
+ specify style for table editor Table[TextField].lineStyleType
+update on added to Jtable for custom editors

Button
TitlePane[Button].border.toAll - disable/enable border for Buttons on TitlePane
Button[border].defaultButton.color - option to set border color for default button

InternalFrameTitlePane
InternalFrameTitlePane[Line].color - property instead of hardcoded GRAY_50

JXMonthView
apply theme to calendar component - unforunately i did it now after setLookAndFeel

Regards
Jarek

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys,

Thanks for your work, there is a lot of new code and before starting the review procedure I should build your code.

Inside your branch, you have missed the class `MaterialConstants`.

The first thing, when I see your code with MaterialConstants, I thought that the class should have the subdivision into component, like this.

```
package mdlaf.utils;

public class MaterialConstants {

    public class TextComponent{

        public static final String CONSTAN = "CONSTAN";

    }
}
```

Why? I think is if we include the constant class inside the library, it should contain all components constant, and if we create a subdivision from component we can have a code organized better, what do you think?

**Comment by jarek-insys** [comment]
Hi Vincent @vincenzopalazzo,

Sorry I missed somehow 2 files when doing synchronization
I comitted them now.

I was doing enum definition up to you to decide

Regards
Jarek

**Comment by jarek-insys** [comment]
Hi Vincent @vincenzopalazzo,

some more things for text componets 

image
image


public class MaterialConstants {

	public enum TextComponent {

+ Viewport backround primary backround

Regards
Jarek

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys,

>Sorry I missed somehow 2 files when doing synchronization
I comitted them now.

Oh don't worry.

>I was doing enum definition up to you to decide

The mine is only an example, I like using the constant string but the enum is cool, for me is good.

>some more things for text componets

Thanks, I'm working on this PR https://github.com/vincenzopalazzo/material-ui-swing/pull/119 and after the integration test, I will start to work on your PR, there are a lot of code and I need a little time, sorry.

Thanks for your work.

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys, please the branch dev was changed, try to fix the conflicts inside the PR.

In the next week, I want start the PR review

**Comment by vincenzopalazzo** [comment]
This PR is 2 years old but contains good code and good improvement for the library. However, it is not incomplete.

Thanks for contributing.

**Pull request closed without merging**
